title: Junchen's blog
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Junchen Wang # add your name
author-img: profile-photo.png # add your photo
about-author: Graduate Student of China University of Geosciences, Wuhan  # add description
twitter: JunChWang
facebook: junchen.wang.140
github: WangJunChen567 # add your Github handle
linkedin: wangjunchenchris
email: wangjunchen@cug.edu.cn # add your Email address

# Disqus
discus-identifier: JC-Wang # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
